name: Rain bow's blog
description: Blogging about Rain-bow
meta_description: "Rain bow's blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /rainbow02
domain_name: "http://rain-bow02.github.io"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "rain-bow02"

# Disqus config
disqus-shortname: ""
